# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d4164c83f20608cba8e715448cfbe93d06e93b2cea7aa4537c74b8f59bc2269875604eb4ba7c4758518e74a400536da2a33d0eb7ba6f42ae170501530846f08

test:
  secret_key_base: ad1ebeae3a8221a952af9651aa86069c4463b53aaf33e137850d2e3dbccb4ffbc3189ec39c7bd15f0b529a61ba6bec2217b3810eb82b6918fbdd3776ea8edf41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
